name: Update release branch

# Run every Sunday @ 13:30 UTC => 6:30 PST
on:
  schedule:
    - cron:  '30 13 * * 0'

jobs:
  update-release-branch:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
    
      - name: Update release branch
        run: |
          git fetch origin
          git reset origin/master --hard
          git push origin release -f
